quarkus:
  http:
    auth:
      basic: true
  datasource:
    db-kind: postgresql
    username: ${PG_LOGIN}
    password: ${PG_PASSWORD}
    jdbc:
      url: jdbc:postgresql://localhost:5432/${PG_DB_NAME}
  hibernate-orm:
    log:
      sql: true
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: 0
  rest-client:
    logging:
      scope: request-response
      body-limit: 2000
    telegram-api:
      url: https://api.telegram.org/bot${app.telegram.bot-token}
    "ru.mitrohinayulya.zabotushka.client.MyGreenwayLoginApi":
      url: https://greenwaystart.com
      follow-redirects: true
    "ru.mitrohinayulya.zabotushka.client.MyGreenwayApi":
      url: https://pyapi.greenwaystart.com/pyapi/v1

app:
  host: ${HOST}
  telegram:
    bot-token: ${TELEGRAM_BOT_TOKEN}
    webhook:
      path: /telegram/webhook
      secret: ${TELEGRAM_WEBHOOK_SECRET}
      enabled: ${TELEGRAM_WEBHOOK_ENABLED:true}
  greenway:
    id: ${GREENWAY_ID:}
    password: ${GREENWAY_PASSWORD:}
  basic-auth:
    username: ${BASIC_AUTH_USERNAME:admin}
    password: ${BASIC_AUTH_PASSWORD:admin}

"%prod":
  rest-client:
    telegram-api:
      url: "https://api.telegram.org/bot${app.telegram.bot-token}"
