quarkus:
  application:
    name: zabotushka
  rate-limiter:
    buckets:
      telegram:
        limits:
          - permitted-uses: ${TELEGRAM_RATE_LIMIT:25}
            period: 1S
  log:
    file:
      path: logs/zabotushka.log
      rotation:
        max-file-size: 10M
        max-backup-index: 7
        file-suffix: .yyyy-MM-dd
  http:
    auth:
      basic: true
  otel:
    logs:
      enabled: ${DEV_ENABLE_OTEL:false}
    metrics:
      enabled: ${DEV_ENABLE_OTEL:false}
    traces:
      enabled: false
  datasource:
    db-kind: postgresql
    username: ${PG_LOGIN}
    password: ${PG_PASSWORD}
    jdbc:
      url: jdbc:postgresql://${PG_HOST}:5432/${PG_DB_NAME}
  flyway:
    migrate-at-start: true
    baseline-on-migrate: true
    baseline-version: 0
  rest-client:
    logging:
      scope: request-response
      body-limit: 2000
    telegram-access-bot-api:
      url: https://api.telegram.org/bot${app.telegram.access-bot-token}
    telegram-message-bot-api:
      url: https://api.telegram.org/bot${app.telegram.message-bot-token}
    max-bot-api:
      url: https://platform-api.max.ru
      headers:
        Authorization: ${app.max.bot-token}
    vk-bot-api:
      url: https://api.vk.com/method
    "ru.mitrohinayulya.zabotushka.client.MyGreenwayLoginApi":
      url: https://greenwaystart.com
      follow-redirects: true
    my-greenway-api:
      url: https://pyapi.greenwaystart.com/pyapi/v1
      headers:
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
        Accept: application/json, text/plain, */*
        sec-ch-ua: '" Not A;Brand";v="99", "Chromium";v="99", "Google Chrome";v="99"'
        sec-ch-ua-mobile: '?0'
        sec-ch-ua-platform: '"Windows"'
        Origin: https://greenwaystart.com
        Referer: https://greenwaystart.com/
        Content-Language: ru-RU

app:
  host: ${HOST}
  telegram:
    access-bot-token: ${TELEGRAM_ACCESS_BOT_TOKEN}
    message-bot-token: ${TELEGRAM_MESSAGE_BOT_TOKEN}
    webhook:
      path: /telegram/webhook
      secret: ${TELEGRAM_ACCESS_BOT_WEBHOOK_SECRET}
      enabled: ${TELEGRAM_ACCESS_BOT_WEBHOOK_ENABLED:true}
  max:
    bot-token: ${MAX_BOT_TOKEN}
    webhook:
      path: /max/webhook
      secret: ${MAX_BOT_WEBHOOK_SECRET}
      enabled: ${MAX_BOT_WEBHOOK_ENABLED:true}
  vk:
    group-id: ${VK_GROUP_ID}
    bot-token: ${VK_BOT_TOKEN}
    webhook:
      path: /vk/webhook
      secret: ${VK_BOT_WEBHOOK_SECRET}
      enabled: ${VK_BOT_WEBHOOK_ENABLED:true}
  greenway:
    id: ${GREENWAY_ID:}
    password: ${GREENWAY_PASSWORD:}
  basic-auth:
    username: ${BASIC_AUTH_USERNAME:admin}
    password: ${BASIC_AUTH_PASSWORD:admin}

"%prod":
  quarkus:
    otel:
      logs:
        enabled: true
      metrics:
        enabled: true
      exporter:
        otlp:
          protocol: http/protobuf
          metrics:
            endpoint: ${OTLP_URL}
            headers: "Authorization=Basic ${OTLP_TOKEN_BASE64}"
          logs:
            endpoint: ${OTLP_URL}
            headers: "Authorization=Basic ${OTLP_TOKEN_BASE64}"
      resource:
        attributes: "deployment.environment=${QUARKUS_PROFILE:dev}"
  rest-client:
    access-bot-api:
      url: "https://api.telegram.org/bot${app.telegram.access-bot-token}"
    message-bot-api:
      url: "https://api.telegram.org/bot${app.telegram.message-bot-token}"
